foundation: fusionx
url: https://www.fusionx.net

colors:
  color1: rgba(32, 145, 208, 1)  # 主蓝色
  color2: rgba(5, 85, 182, 1)     # 深蓝色
  color3: rgba(32, 145, 208, 1)   # 同主蓝
  color4: rgba(32, 145, 208, 0.9) # 半透明主蓝
  color5: rgba(32, 145, 208, 0.85)
  color6: rgba(52, 198, 243, 0.85) # 青蓝色
  color7: rgba(232, 244, 250, 1)
footer: # 页脚
  links:
    github: https://github.com/openfusionx/FXView
    homepage: https://www.fusionx.net
  logo: https://fxfiles.oss-cn-beijing.aliyuncs.com/openfxview/white_logo.svg
header:
  links:
    github: https://github.com/openfusionx/FXView
  logo: https://fxfiles.oss-cn-beijing.aliyuncs.com/openfxview/yunwanghu.svg
screenshot_width: 1500

featured_items:
  - field: maturity
    options:
      - value: level1
        order: 1
        label: level1
      - value: level2
        order: 2
        label: level2
      - value: level3
        order: 3
        label: level3


grid_items_size: medium

groups:
  - name: Open公司
    categories:
      - Application应用层


members_category: 会员