name: Landscape2 Build & Deploy
on:
  push:
    branches: [ "landscape" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Landscape2
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf \
          https://github.com/cncf/landscape2/releases/download/v1.0.0/landscape2-installer.sh | sh

      - name: Build Project
        run: |
          landscape2 build \
            --data-file landscape.yml \
            --settings-file settings.yml \
            --logos-path ./logos/ \
            --output-dir build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登陆到阿里云 ACR服务
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALICLOUD_ACR_REGISTRY }}
          username: ${{ secrets.ALICLOUD_ACR_USERNAME }}
          password: ${{ secrets.ALICLOUD_ACR_PASSWORD }}

      - name: 构建并打包成镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ALICLOUD_ACR_REGISTRY }}/fxview/open_fxview:v1.0.0